### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/kinesis-example-scala-consumer#4]
Can remove:

> Please note: Amazon Kinesis is currently in private beta. Being on the Kinesis private beta is a pre-requisite to building and running this project.

And:

>    Now manually copy the relevant jar from your Amazon Kinesis SDK Preview:
> 
>    $ cd kinesis-example-scala-producer
>    $ cp ~/downloads/AmazonKinesisSDK-preview/aws-java-sdk-1.6.4/lib/aws-java-sdk-1.6.4.jar lib/
>    $ sbt assembly

**Comment by bamos** [comment]
Hi Alex, should we keep `FAQ` and `Roadmap`? Also, just curious, does this say to use `sbt assembly` then `java -jar` rather than `sbt run` to avoid `sbt` overhead, or is there another reason?

**Comment by alexanderdean** [comment]
Ah right - do remove `FAQ` and `Roadmap` by all means.

The suggestions around assembly and `java -jar` are so that people can turn these into deployable fat jars and run them on a server without sbt - but I agree, that doesn't make a whole lot of sense for 'test' apps like these.

I think it would make total sense to remove these instructions and revert to `sbt run`. (Whereas for an actual app like the Scala Stream Collector, making a fatjar for deployment does make a lot of sense)...

**Comment by bamos** [comment]
Changed, and I've left the `sbt assembly` dependency just in case somebody still wants it. Let me know if there's anything else on the README!

**Comment by alexanderdean** [comment]
Nice one. Good idea keeping the sbt-assembly dep as someone may want to fork and evolve this into their own app, then they have the sbt-assembly ready to use...
