### ISSUE TITLE
Add real-time processing as an option to our consumer.

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/kinesis-example-scala-consumer#5]
As per @bamos' explanation in #1:

> Scalazon and this example uses TRIM_HORIZON, which starts the iterator at the 
> beginning of the stream, but using LATEST also seems helpful, especially since 
> we're interested in real-time processing.
> The documentation reads like a real-time consumer application should continuously
> poll for new data, but I haven't tried anything myself.

**Comment by bamos** [comment]
Hi @alexanderdean, I've merged everything into the `feature/bamos-updates` branch and everything's working smoothly for these issues. Please open (or reopen) if you want me to change anything on the Kinesis consumer.
